services:
  nginx:
    image: nginx-nginx:latest
    build:
      context: ./infra/
      args:
        BUILD_ARGUMENT_ENV: dev
      dockerfile: ./nginx/Dockerfile
    restart: always
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - ./code:/var/www/html:ro,cached
      - ./infra/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - symfony
    networks:
      - symfony

  symfony:
    image: php-symfony:latest
    build:
      context: ./infra/
      dockerfile: ./php/Dockerfile
    volumes:
      - ./code:/var/www/html:cached
      - ./infra/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./infra/php/config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres
    networks:
      - symfony

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: logparser
      POSTGRES_USER: zakiazhari
      POSTGRES_PASSWORD: zaki
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - symfony

  adminer:
    image: adminer:4
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - symfony

  mailcatcher:
    networks:
      - symfony
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  postgres_data:

networks:
  symfony:
    name: symfony